//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class AboutPage : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._Image = this.transform.Find("Image").GetComponent<Image>();
            this._AboutImage = this.transform.Find("About").GetComponent<Image>();
            this._TitleText = this.transform.Find("About").Find("Left").Find("Title").GetComponent<Text>();
            this._Scroll_View = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").GetComponent<ScrollRect>();
            this._ContentVerticalLayoutGroup = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").GetComponent<VerticalLayoutGroup>();
            this._StaffText = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").Find("StaffText").GetComponent<Text>();
            this._Right_TitleText = this.transform.Find("About").Find("Right").Find("Title").GetComponent<Text>();
            this._Container_Scroll_View = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").GetComponent<ScrollRect>();
            this._Viewport_ContentVerticalLayoutGroup = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").GetComponent<VerticalLayoutGroup>();
            this._LicenseText = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").Find("LicenseText").GetComponent<Text>();
            this._BackButtonBlack = this.transform.Find("About").Find("Back").GetComponent<ButtonBlack>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image _Image;
        public Image Image
        {
            get
            {
                if ((this._Image == null))
                {
                    this._Image = this.transform.Find("Image").GetComponent<Image>();
                }
                return this._Image;
            }
        }
        [SerializeField()]
        private Image _AboutImage;
        public Image AboutImage
        {
            get
            {
                if ((this._AboutImage == null))
                {
                    this._AboutImage = this.transform.Find("About").GetComponent<Image>();
                }
                return this._AboutImage;
            }
        }
        [SerializeField()]
        private Text _TitleText;
        public Text TitleText
        {
            get
            {
                if ((this._TitleText == null))
                {
                    this._TitleText = this.transform.Find("About").Find("Left").Find("Title").GetComponent<Text>();
                }
                return this._TitleText;
            }
        }
        [SerializeField()]
        private ScrollRect _Scroll_View;
        public ScrollRect Scroll_View
        {
            get
            {
                if ((this._Scroll_View == null))
                {
                    this._Scroll_View = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").GetComponent<ScrollRect>();
                }
                return this._Scroll_View;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _ContentVerticalLayoutGroup;
        public VerticalLayoutGroup ContentVerticalLayoutGroup
        {
            get
            {
                if ((this._ContentVerticalLayoutGroup == null))
                {
                    this._ContentVerticalLayoutGroup = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").GetComponent<VerticalLayoutGroup>();
                }
                return this._ContentVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private Text _StaffText;
        public Text StaffText
        {
            get
            {
                if ((this._StaffText == null))
                {
                    this._StaffText = this.transform.Find("About").Find("Left").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").Find("StaffText").GetComponent<Text>();
                }
                return this._StaffText;
            }
        }
        [SerializeField()]
        private Text _Right_TitleText;
        public Text Right_TitleText
        {
            get
            {
                if ((this._Right_TitleText == null))
                {
                    this._Right_TitleText = this.transform.Find("About").Find("Right").Find("Title").GetComponent<Text>();
                }
                return this._Right_TitleText;
            }
        }
        [SerializeField()]
        private ScrollRect _Container_Scroll_View;
        public ScrollRect Container_Scroll_View
        {
            get
            {
                if ((this._Container_Scroll_View == null))
                {
                    this._Container_Scroll_View = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").GetComponent<ScrollRect>();
                }
                return this._Container_Scroll_View;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _Viewport_ContentVerticalLayoutGroup;
        public VerticalLayoutGroup Viewport_ContentVerticalLayoutGroup
        {
            get
            {
                if ((this._Viewport_ContentVerticalLayoutGroup == null))
                {
                    this._Viewport_ContentVerticalLayoutGroup = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").GetComponent<VerticalLayoutGroup>();
                }
                return this._Viewport_ContentVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private Text _LicenseText;
        public Text LicenseText
        {
            get
            {
                if ((this._LicenseText == null))
                {
                    this._LicenseText = this.transform.Find("About").Find("Right").Find("Container").Find("Scroll View").Find("Viewport").Find("Content").Find("LicenseText").GetComponent<Text>();
                }
                return this._LicenseText;
            }
        }
        [SerializeField()]
        private ButtonBlack _BackButtonBlack;
        public ButtonBlack BackButtonBlack
        {
            get
            {
                if ((this._BackButtonBlack == null))
                {
                    this._BackButtonBlack = this.transform.Find("About").Find("Back").GetComponent<ButtonBlack>();
                }
                return this._BackButtonBlack;
            }
        }
        partial void onAwake();
    }
}
