//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class BuildCardList : UIList<BuildCardListItem>
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.defaultItem.gameObject.SetActive(false);
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_GridLayoutGroup = this.GetComponent<GridLayoutGroup>();
            this.defaultItem = this.transform.Find("BuildCardListItem").GetComponent<BuildCardListItem>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.parent.parent.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private GridLayoutGroup m_as_GridLayoutGroup;
        public GridLayoutGroup asGridLayoutGroup
        {
            get
            {
                if ((this.m_as_GridLayoutGroup == null))
                {
                    this.m_as_GridLayoutGroup = this.GetComponent<GridLayoutGroup>();
                }
                return this.m_as_GridLayoutGroup;
            }
        }
        protected override BuildCardListItem getDefaultItem()
        {
            return this.transform.Find("BuildCardListItem").GetComponent<BuildCardListItem>();
        }
        partial void onAwake();
    }
}
