//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Build : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._BackgroundImage = this.transform.Find("Background").GetComponent<Image>();
            this._MasterButton = this.transform.Find("MasterButton").GetComponent<Button>();
            this._NameBkgImage = this.transform.Find("NameBkgImage").GetComponent<Image>();
            this._MasterNameText = this.transform.Find("NameBkgImage").Find("MasterNameText").GetComponent<Text>();
            this._DeckCountText = this.transform.Find("NameBkgImage").Find("DeckCountText").GetComponent<Text>();
            this._DeckViewScroll = this.transform.Find("DeckView").GetComponent<ScrollRect>();
            this._BuildDeckList = this.transform.Find("DeckView").Find("Viewport").Find("BuildDeckList").GetComponent<BuildDeckList>();
            this._CardViewScroll = this.transform.Find("CardView").GetComponent<ScrollRect>();
            this._BuildCardList = this.transform.Find("CardView").Find("Viewport").Find("BuildCardList").GetComponent<BuildCardList>();
            this._ReturnButton = this.transform.Find("ReturnButton").GetComponent<Button>();
            this._DragCard = this.transform.Find("DragCard").GetComponent<DragCard>();
            this._FilterPanel = this.transform.Find("FilterPanel").GetComponent<FilterPanel>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image _BackgroundImage;
        public Image BackgroundImage
        {
            get
            {
                if ((this._BackgroundImage == null))
                {
                    this._BackgroundImage = this.transform.Find("Background").GetComponent<Image>();
                }
                return this._BackgroundImage;
            }
        }
        [SerializeField()]
        private Button _MasterButton;
        public Button MasterButton
        {
            get
            {
                if ((this._MasterButton == null))
                {
                    this._MasterButton = this.transform.Find("MasterButton").GetComponent<Button>();
                }
                return this._MasterButton;
            }
        }
        [SerializeField()]
        private Image _NameBkgImage;
        public Image NameBkgImage
        {
            get
            {
                if ((this._NameBkgImage == null))
                {
                    this._NameBkgImage = this.transform.Find("NameBkgImage").GetComponent<Image>();
                }
                return this._NameBkgImage;
            }
        }
        [SerializeField()]
        private Text _MasterNameText;
        public Text MasterNameText
        {
            get
            {
                if ((this._MasterNameText == null))
                {
                    this._MasterNameText = this.transform.Find("NameBkgImage").Find("MasterNameText").GetComponent<Text>();
                }
                return this._MasterNameText;
            }
        }
        [SerializeField()]
        private Text _DeckCountText;
        public Text DeckCountText
        {
            get
            {
                if ((this._DeckCountText == null))
                {
                    this._DeckCountText = this.transform.Find("NameBkgImage").Find("DeckCountText").GetComponent<Text>();
                }
                return this._DeckCountText;
            }
        }
        [SerializeField()]
        private ScrollRect _DeckViewScroll;
        public ScrollRect DeckViewScroll
        {
            get
            {
                if ((this._DeckViewScroll == null))
                {
                    this._DeckViewScroll = this.transform.Find("DeckView").GetComponent<ScrollRect>();
                }
                return this._DeckViewScroll;
            }
        }
        [SerializeField()]
        private BuildDeckList _BuildDeckList;
        public BuildDeckList BuildDeckList
        {
            get
            {
                if ((this._BuildDeckList == null))
                {
                    this._BuildDeckList = this.transform.Find("DeckView").Find("Viewport").Find("BuildDeckList").GetComponent<BuildDeckList>();
                }
                return this._BuildDeckList;
            }
        }
        [SerializeField()]
        private ScrollRect _CardViewScroll;
        public ScrollRect CardViewScroll
        {
            get
            {
                if ((this._CardViewScroll == null))
                {
                    this._CardViewScroll = this.transform.Find("CardView").GetComponent<ScrollRect>();
                }
                return this._CardViewScroll;
            }
        }
        [SerializeField()]
        private BuildCardList _BuildCardList;
        public BuildCardList BuildCardList
        {
            get
            {
                if ((this._BuildCardList == null))
                {
                    this._BuildCardList = this.transform.Find("CardView").Find("Viewport").Find("BuildCardList").GetComponent<BuildCardList>();
                }
                return this._BuildCardList;
            }
        }
        [SerializeField()]
        private Button _ReturnButton;
        public Button ReturnButton
        {
            get
            {
                if ((this._ReturnButton == null))
                {
                    this._ReturnButton = this.transform.Find("ReturnButton").GetComponent<Button>();
                }
                return this._ReturnButton;
            }
        }
        [SerializeField()]
        private DragCard _DragCard;
        public DragCard DragCard
        {
            get
            {
                if ((this._DragCard == null))
                {
                    this._DragCard = this.transform.Find("DragCard").GetComponent<DragCard>();
                }
                return this._DragCard;
            }
        }
        [SerializeField()]
        private FilterPanel _FilterPanel;
        public FilterPanel FilterPanel
        {
            get
            {
                if ((this._FilterPanel == null))
                {
                    this._FilterPanel = this.transform.Find("FilterPanel").GetComponent<FilterPanel>();
                }
                return this._FilterPanel;
            }
        }
        partial void onAwake();
    }
}
