//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Card : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._CardBackImage = this.transform.Find("CardBack").GetComponent<Image>();
            this._Image_1 = this.transform.Find("CardBack").Find("Image_1").GetComponent<Image>();
            this._Image_2 = this.transform.Find("CardBack").Find("Image_2").GetComponent<Image>();
            this._ShadowImage = this.transform.Find("CardFace").Find("Shadow").GetComponent<Image>();
            this._Mask = this.transform.Find("CardFace").Find("Mask").GetComponent<Mask>();
            this._Image = this.transform.Find("CardFace").Find("Mask").Find("Image").GetComponent<Image>();
            this._NameImage = this.transform.Find("CardFace").Find("Mask").Find("Name").GetComponent<Image>();
            this._NameText = this.transform.Find("CardFace").Find("Mask").Find("Name").Find("NameText").GetComponent<Text>();
            this._DescImage = this.transform.Find("CardFace").Find("Mask").Find("Desc").GetComponent<Image>();
            this._DescText = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("DescText").GetComponent<Text>();
            this._FieldImage = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field").GetComponent<Image>();
            this._Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field").Find("Text").GetComponent<Text>();
            this._Field_1Image = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (1)").GetComponent<Image>();
            this._Field_1_Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (1)").Find("Text").GetComponent<Text>();
            this._Field_2Image = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (2)").GetComponent<Image>();
            this._Field_2_Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (2)").Find("Text").GetComponent<Text>();
            this._BorderImage = this.transform.Find("CardFace").Find("Border").GetComponent<Image>();
            this._CardFace_Image = this.transform.Find("CardFace").Find("Image").GetComponent<Image>();
            this._CostImage = this.transform.Find("CardFace").Find("CostImage").GetComponent<Image>();
            this._CostText = this.transform.Find("CardFace").Find("CostText").GetComponent<Text>();
            this._AttackImage = this.transform.Find("CardFace").Find("AttackImage").GetComponent<Image>();
            this._AttackText = this.transform.Find("CardFace").Find("AttackText").GetComponent<Text>();
            this._LifeImage = this.transform.Find("CardFace").Find("LifeImage").GetComponent<Image>();
            this._LifeText = this.transform.Find("CardFace").Find("LifeText").GetComponent<Text>();
        }
        [SerializeField()]
        private Image _CardBackImage;
        public Image CardBackImage
        {
            get
            {
                if ((this._CardBackImage == null))
                {
                    this._CardBackImage = this.transform.Find("CardBack").GetComponent<Image>();
                }
                return this._CardBackImage;
            }
        }
        [SerializeField()]
        private Image _Image_1;
        public Image Image_1
        {
            get
            {
                if ((this._Image_1 == null))
                {
                    this._Image_1 = this.transform.Find("CardBack").Find("Image_1").GetComponent<Image>();
                }
                return this._Image_1;
            }
        }
        [SerializeField()]
        private Image _Image_2;
        public Image Image_2
        {
            get
            {
                if ((this._Image_2 == null))
                {
                    this._Image_2 = this.transform.Find("CardBack").Find("Image_2").GetComponent<Image>();
                }
                return this._Image_2;
            }
        }
        [SerializeField()]
        private Image _ShadowImage;
        public Image ShadowImage
        {
            get
            {
                if ((this._ShadowImage == null))
                {
                    this._ShadowImage = this.transform.Find("CardFace").Find("Shadow").GetComponent<Image>();
                }
                return this._ShadowImage;
            }
        }
        [SerializeField()]
        private Mask _Mask;
        public Mask Mask
        {
            get
            {
                if ((this._Mask == null))
                {
                    this._Mask = this.transform.Find("CardFace").Find("Mask").GetComponent<Mask>();
                }
                return this._Mask;
            }
        }
        [SerializeField()]
        private Image _Image;
        public Image Image
        {
            get
            {
                if ((this._Image == null))
                {
                    this._Image = this.transform.Find("CardFace").Find("Mask").Find("Image").GetComponent<Image>();
                }
                return this._Image;
            }
        }
        [SerializeField()]
        private Image _NameImage;
        public Image NameImage
        {
            get
            {
                if ((this._NameImage == null))
                {
                    this._NameImage = this.transform.Find("CardFace").Find("Mask").Find("Name").GetComponent<Image>();
                }
                return this._NameImage;
            }
        }
        [SerializeField()]
        private Text _NameText;
        public Text NameText
        {
            get
            {
                if ((this._NameText == null))
                {
                    this._NameText = this.transform.Find("CardFace").Find("Mask").Find("Name").Find("NameText").GetComponent<Text>();
                }
                return this._NameText;
            }
        }
        [SerializeField()]
        private Image _DescImage;
        public Image DescImage
        {
            get
            {
                if ((this._DescImage == null))
                {
                    this._DescImage = this.transform.Find("CardFace").Find("Mask").Find("Desc").GetComponent<Image>();
                }
                return this._DescImage;
            }
        }
        [SerializeField()]
        private Text _DescText;
        public Text DescText
        {
            get
            {
                if ((this._DescText == null))
                {
                    this._DescText = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("DescText").GetComponent<Text>();
                }
                return this._DescText;
            }
        }
        [SerializeField()]
        private Image _FieldImage;
        public Image FieldImage
        {
            get
            {
                if ((this._FieldImage == null))
                {
                    this._FieldImage = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field").GetComponent<Image>();
                }
                return this._FieldImage;
            }
        }
        [SerializeField()]
        private Text _Text;
        public Text Text
        {
            get
            {
                if ((this._Text == null))
                {
                    this._Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field").Find("Text").GetComponent<Text>();
                }
                return this._Text;
            }
        }
        [SerializeField()]
        private Image _Field_1Image;
        public Image Field_1Image
        {
            get
            {
                if ((this._Field_1Image == null))
                {
                    this._Field_1Image = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (1)").GetComponent<Image>();
                }
                return this._Field_1Image;
            }
        }
        [SerializeField()]
        private Text _Field_1_Text;
        public Text Field_1_Text
        {
            get
            {
                if ((this._Field_1_Text == null))
                {
                    this._Field_1_Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (1)").Find("Text").GetComponent<Text>();
                }
                return this._Field_1_Text;
            }
        }
        [SerializeField()]
        private Image _Field_2Image;
        public Image Field_2Image
        {
            get
            {
                if ((this._Field_2Image == null))
                {
                    this._Field_2Image = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (2)").GetComponent<Image>();
                }
                return this._Field_2Image;
            }
        }
        [SerializeField()]
        private Text _Field_2_Text;
        public Text Field_2_Text
        {
            get
            {
                if ((this._Field_2_Text == null))
                {
                    this._Field_2_Text = this.transform.Find("CardFace").Find("Mask").Find("Desc").Find("Field (2)").Find("Text").GetComponent<Text>();
                }
                return this._Field_2_Text;
            }
        }
        [SerializeField()]
        private Image _BorderImage;
        public Image BorderImage
        {
            get
            {
                if ((this._BorderImage == null))
                {
                    this._BorderImage = this.transform.Find("CardFace").Find("Border").GetComponent<Image>();
                }
                return this._BorderImage;
            }
        }
        [SerializeField()]
        private Image _CardFace_Image;
        public Image CardFace_Image
        {
            get
            {
                if ((this._CardFace_Image == null))
                {
                    this._CardFace_Image = this.transform.Find("CardFace").Find("Image").GetComponent<Image>();
                }
                return this._CardFace_Image;
            }
        }
        [SerializeField()]
        private Image _CostImage;
        public Image CostImage
        {
            get
            {
                if ((this._CostImage == null))
                {
                    this._CostImage = this.transform.Find("CardFace").Find("CostImage").GetComponent<Image>();
                }
                return this._CostImage;
            }
        }
        [SerializeField()]
        private Text _CostText;
        public Text CostText
        {
            get
            {
                if ((this._CostText == null))
                {
                    this._CostText = this.transform.Find("CardFace").Find("CostText").GetComponent<Text>();
                }
                return this._CostText;
            }
        }
        [SerializeField()]
        private Image _AttackImage;
        public Image AttackImage
        {
            get
            {
                if ((this._AttackImage == null))
                {
                    this._AttackImage = this.transform.Find("CardFace").Find("AttackImage").GetComponent<Image>();
                }
                return this._AttackImage;
            }
        }
        [SerializeField()]
        private Text _AttackText;
        public Text AttackText
        {
            get
            {
                if ((this._AttackText == null))
                {
                    this._AttackText = this.transform.Find("CardFace").Find("AttackText").GetComponent<Text>();
                }
                return this._AttackText;
            }
        }
        [SerializeField()]
        private Image _LifeImage;
        public Image LifeImage
        {
            get
            {
                if ((this._LifeImage == null))
                {
                    this._LifeImage = this.transform.Find("CardFace").Find("LifeImage").GetComponent<Image>();
                }
                return this._LifeImage;
            }
        }
        [SerializeField()]
        private Text _LifeText;
        public Text LifeText
        {
            get
            {
                if ((this._LifeText == null))
                {
                    this._LifeText = this.transform.Find("CardFace").Find("LifeText").GetComponent<Text>();
                }
                return this._LifeText;
            }
        }
        partial void onAwake();
        public enum IsFaceup
        {
            False,
            True,
        }
        public IsFaceup IsFaceupController
        {
            get
            {
                return ((IsFaceup)(Enum.Parse(typeof(IsFaceup), this.getController("IsFaceup", Enum.GetNames(typeof(IsFaceup))))));
            }
            set
            {
                this.setController("IsFaceup", Enum.GetName(typeof(IsFaceup), value));
            }
        }
        public enum Type
        {
            Servant,
            Spell,
        }
        public Type TypeController
        {
            get
            {
                return ((Type)(Enum.Parse(typeof(Type), this.getController("Type", Enum.GetNames(typeof(Type))))));
            }
            set
            {
                this.setController("Type", Enum.GetName(typeof(Type), value));
            }
        }
    }
}
