//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class ControlPanel : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._BtnGroupVerticalLayoutGroup = this.transform.Find("BtnGroup").GetComponent<VerticalLayoutGroup>();
            this._LANButton = this.transform.Find("BtnGroup").Find("LAN").GetComponent<Button>();
            this._WANButton = this.transform.Find("BtnGroup").Find("WAN").GetComponent<Button>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _BtnGroupVerticalLayoutGroup;
        public VerticalLayoutGroup BtnGroupVerticalLayoutGroup
        {
            get
            {
                if ((this._BtnGroupVerticalLayoutGroup == null))
                {
                    this._BtnGroupVerticalLayoutGroup = this.transform.Find("BtnGroup").GetComponent<VerticalLayoutGroup>();
                }
                return this._BtnGroupVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private Button _LANButton;
        public Button LANButton
        {
            get
            {
                if ((this._LANButton == null))
                {
                    this._LANButton = this.transform.Find("BtnGroup").Find("LAN").GetComponent<Button>();
                }
                return this._LANButton;
            }
        }
        [SerializeField()]
        private Button _WANButton;
        public Button WANButton
        {
            get
            {
                if ((this._WANButton == null))
                {
                    this._WANButton = this.transform.Find("BtnGroup").Find("WAN").GetComponent<Button>();
                }
                return this._WANButton;
            }
        }
        partial void onAwake();
    }
}
