//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Deck : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._Card_1 = this.transform.Find("Card (1)").GetComponent<Card>();
            this._Card_2 = this.transform.Find("Card (2)").GetComponent<Card>();
            this._Card_3 = this.transform.Find("Card (3)").GetComponent<Card>();
            this._Card_4 = this.transform.Find("Card (4)").GetComponent<Card>();
            this._Card_5 = this.transform.Find("Card (5)").GetComponent<Card>();
        }
        [SerializeField()]
        private Card _Card_1;
        public Card Card_1
        {
            get
            {
                if ((this._Card_1 == null))
                {
                    this._Card_1 = this.transform.Find("Card (1)").GetComponent<Card>();
                }
                return this._Card_1;
            }
        }
        [SerializeField()]
        private Card _Card_2;
        public Card Card_2
        {
            get
            {
                if ((this._Card_2 == null))
                {
                    this._Card_2 = this.transform.Find("Card (2)").GetComponent<Card>();
                }
                return this._Card_2;
            }
        }
        [SerializeField()]
        private Card _Card_3;
        public Card Card_3
        {
            get
            {
                if ((this._Card_3 == null))
                {
                    this._Card_3 = this.transform.Find("Card (3)").GetComponent<Card>();
                }
                return this._Card_3;
            }
        }
        [SerializeField()]
        private Card _Card_4;
        public Card Card_4
        {
            get
            {
                if ((this._Card_4 == null))
                {
                    this._Card_4 = this.transform.Find("Card (4)").GetComponent<Card>();
                }
                return this._Card_4;
            }
        }
        [SerializeField()]
        private Card _Card_5;
        public Card Card_5
        {
            get
            {
                if ((this._Card_5 == null))
                {
                    this._Card_5 = this.transform.Find("Card (5)").GetComponent<Card>();
                }
                return this._Card_5;
            }
        }
        partial void onAwake();
    }
}
