//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class DialogButtonList : UIList<DialogButtonListItem>
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.defaultItem.gameObject.SetActive(false);
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_HorizontalLayoutGroup = this.GetComponent<HorizontalLayoutGroup>();
            this.defaultItem = this.transform.Find("DialogButtonListItem").GetComponent<DialogButtonListItem>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.parent.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private HorizontalLayoutGroup m_as_HorizontalLayoutGroup;
        public HorizontalLayoutGroup asHorizontalLayoutGroup
        {
            get
            {
                if ((this.m_as_HorizontalLayoutGroup == null))
                {
                    this.m_as_HorizontalLayoutGroup = this.GetComponent<HorizontalLayoutGroup>();
                }
                return this.m_as_HorizontalLayoutGroup;
            }
        }
        protected override DialogButtonListItem getDefaultItem()
        {
            return this.transform.Find("DialogButtonListItem").GetComponent<DialogButtonListItem>();
        }
        partial void onAwake();
    }
}
