//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class DialogButtonListItem : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Button = this.GetComponent<Button>();
            this.m_as_Image = this.GetComponent<Image>();
            this._Text = this.transform.Find("Text").GetComponent<Text>();
        }
        private DialogButtonList _parent;
        public DialogButtonList parent
        {
            get
            {
                return this.transform.parent.GetComponent<DialogButtonList>();
            }
        }
        [SerializeField()]
        private Button m_as_Button;
        public Button asButton
        {
            get
            {
                if ((this.m_as_Button == null))
                {
                    this.m_as_Button = this.GetComponent<Button>();
                }
                return this.m_as_Button;
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Text _Text;
        public Text Text
        {
            get
            {
                if ((this._Text == null))
                {
                    this._Text = this.transform.Find("Text").GetComponent<Text>();
                }
                return this._Text;
            }
        }
        partial void onAwake();
    }
}
