//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Discover : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._PanelImage = this.transform.Find("Panel").GetComponent<Image>();
            this._HoriCardList = this.transform.Find("Panel").Find("HoriCardList").GetComponent<HoriCardList>();
            this._Button = this.transform.Find("Button").GetComponent<Button>();
        }
        [SerializeField()]
        private Image _PanelImage;
        public Image PanelImage
        {
            get
            {
                if ((this._PanelImage == null))
                {
                    this._PanelImage = this.transform.Find("Panel").GetComponent<Image>();
                }
                return this._PanelImage;
            }
        }
        [SerializeField()]
        private HoriCardList _HoriCardList;
        public HoriCardList HoriCardList
        {
            get
            {
                if ((this._HoriCardList == null))
                {
                    this._HoriCardList = this.transform.Find("Panel").Find("HoriCardList").GetComponent<HoriCardList>();
                }
                return this._HoriCardList;
            }
        }
        [SerializeField()]
        private Button _Button;
        public Button Button
        {
            get
            {
                if ((this._Button == null))
                {
                    this._Button = this.transform.Find("Button").GetComponent<Button>();
                }
                return this._Button;
            }
        }
        partial void onAwake();
    }
}
