//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Field : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_ListLayoutGroup = this.GetComponent<ListLayoutGroup>();
            this._Servant = this.transform.Find("Servant").GetComponent<Servant>();
            this._Servant_1 = this.transform.Find("Servant (1)").GetComponent<Servant>();
            this._Servant_2 = this.transform.Find("Servant (2)").GetComponent<Servant>();
            this._Servant_3 = this.transform.Find("Servant (3)").GetComponent<Servant>();
            this._Servant_4 = this.transform.Find("Servant (4)").GetComponent<Servant>();
            this._Servant_5 = this.transform.Find("Servant (5)").GetComponent<Servant>();
            this._Servant_6 = this.transform.Find("Servant (6)").GetComponent<Servant>();
        }
        [SerializeField()]
        private ListLayoutGroup m_as_ListLayoutGroup;
        public ListLayoutGroup asListLayoutGroup
        {
            get
            {
                if ((this.m_as_ListLayoutGroup == null))
                {
                    this.m_as_ListLayoutGroup = this.GetComponent<ListLayoutGroup>();
                }
                return this.m_as_ListLayoutGroup;
            }
        }
        [SerializeField()]
        private Servant _Servant;
        public Servant Servant
        {
            get
            {
                if ((this._Servant == null))
                {
                    this._Servant = this.transform.Find("Servant").GetComponent<Servant>();
                }
                return this._Servant;
            }
        }
        [SerializeField()]
        private Servant _Servant_1;
        public Servant Servant_1
        {
            get
            {
                if ((this._Servant_1 == null))
                {
                    this._Servant_1 = this.transform.Find("Servant (1)").GetComponent<Servant>();
                }
                return this._Servant_1;
            }
        }
        [SerializeField()]
        private Servant _Servant_2;
        public Servant Servant_2
        {
            get
            {
                if ((this._Servant_2 == null))
                {
                    this._Servant_2 = this.transform.Find("Servant (2)").GetComponent<Servant>();
                }
                return this._Servant_2;
            }
        }
        [SerializeField()]
        private Servant _Servant_3;
        public Servant Servant_3
        {
            get
            {
                if ((this._Servant_3 == null))
                {
                    this._Servant_3 = this.transform.Find("Servant (3)").GetComponent<Servant>();
                }
                return this._Servant_3;
            }
        }
        [SerializeField()]
        private Servant _Servant_4;
        public Servant Servant_4
        {
            get
            {
                if ((this._Servant_4 == null))
                {
                    this._Servant_4 = this.transform.Find("Servant (4)").GetComponent<Servant>();
                }
                return this._Servant_4;
            }
        }
        [SerializeField()]
        private Servant _Servant_5;
        public Servant Servant_5
        {
            get
            {
                if ((this._Servant_5 == null))
                {
                    this._Servant_5 = this.transform.Find("Servant (5)").GetComponent<Servant>();
                }
                return this._Servant_5;
            }
        }
        [SerializeField()]
        private Servant _Servant_6;
        public Servant Servant_6
        {
            get
            {
                if ((this._Servant_6 == null))
                {
                    this._Servant_6 = this.transform.Find("Servant (6)").GetComponent<Servant>();
                }
                return this._Servant_6;
            }
        }
        partial void onAwake();
    }
}
