//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class FieldList : UIList<Servant>
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.defaultItem.gameObject.SetActive(false);
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_ListLayoutGroup = this.GetComponent<ListLayoutGroup>();
            this.defaultItem = this.transform.Find("Servant").GetComponent<Servant>();
        }
        [SerializeField()]
        private ListLayoutGroup m_as_ListLayoutGroup;
        public ListLayoutGroup asListLayoutGroup
        {
            get
            {
                if ((this.m_as_ListLayoutGroup == null))
                {
                    this.m_as_ListLayoutGroup = this.GetComponent<ListLayoutGroup>();
                }
                return this.m_as_ListLayoutGroup;
            }
        }
        protected override Servant getDefaultItem()
        {
            return this.transform.Find("Servant").GetComponent<Servant>();
        }
        partial void onAwake();
    }
}
