//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class FilterPanel : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._LabelSearchText = this.transform.Find("LabelSearch").GetComponent<Text>();
            this._DropdownSort = this.transform.Find("DropdownSort").GetComponent<Dropdown>();
            this._LabelCharacterText = this.transform.Find("LabelCharacter").GetComponent<Text>();
            this._DropdownCharacter = this.transform.Find("DropdownCharacter").GetComponent<Dropdown>();
            this._LabelCostText = this.transform.Find("LabelCost").GetComponent<Text>();
            this._DropdownCost = this.transform.Find("DropdownCost").GetComponent<Dropdown>();
            this._LabelRareText = this.transform.Find("LabelRare").GetComponent<Text>();
            this._DropdownRare = this.transform.Find("DropdownRare").GetComponent<Dropdown>();
            this._LabelTypeText = this.transform.Find("LabelType").GetComponent<Text>();
            this._DropdownType = this.transform.Find("DropdownType").GetComponent<Dropdown>();
            this._LabelSortText = this.transform.Find("LabelSort").GetComponent<Text>();
            this._InputField = this.transform.Find("InputField").GetComponent<InputField>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Text _LabelSearchText;
        public Text LabelSearchText
        {
            get
            {
                if ((this._LabelSearchText == null))
                {
                    this._LabelSearchText = this.transform.Find("LabelSearch").GetComponent<Text>();
                }
                return this._LabelSearchText;
            }
        }
        [SerializeField()]
        private Dropdown _DropdownSort;
        public Dropdown DropdownSort
        {
            get
            {
                if ((this._DropdownSort == null))
                {
                    this._DropdownSort = this.transform.Find("DropdownSort").GetComponent<Dropdown>();
                }
                return this._DropdownSort;
            }
        }
        [SerializeField()]
        private Text _LabelCharacterText;
        public Text LabelCharacterText
        {
            get
            {
                if ((this._LabelCharacterText == null))
                {
                    this._LabelCharacterText = this.transform.Find("LabelCharacter").GetComponent<Text>();
                }
                return this._LabelCharacterText;
            }
        }
        [SerializeField()]
        private Dropdown _DropdownCharacter;
        public Dropdown DropdownCharacter
        {
            get
            {
                if ((this._DropdownCharacter == null))
                {
                    this._DropdownCharacter = this.transform.Find("DropdownCharacter").GetComponent<Dropdown>();
                }
                return this._DropdownCharacter;
            }
        }
        [SerializeField()]
        private Text _LabelCostText;
        public Text LabelCostText
        {
            get
            {
                if ((this._LabelCostText == null))
                {
                    this._LabelCostText = this.transform.Find("LabelCost").GetComponent<Text>();
                }
                return this._LabelCostText;
            }
        }
        [SerializeField()]
        private Dropdown _DropdownCost;
        public Dropdown DropdownCost
        {
            get
            {
                if ((this._DropdownCost == null))
                {
                    this._DropdownCost = this.transform.Find("DropdownCost").GetComponent<Dropdown>();
                }
                return this._DropdownCost;
            }
        }
        [SerializeField()]
        private Text _LabelRareText;
        public Text LabelRareText
        {
            get
            {
                if ((this._LabelRareText == null))
                {
                    this._LabelRareText = this.transform.Find("LabelRare").GetComponent<Text>();
                }
                return this._LabelRareText;
            }
        }
        [SerializeField()]
        private Dropdown _DropdownRare;
        public Dropdown DropdownRare
        {
            get
            {
                if ((this._DropdownRare == null))
                {
                    this._DropdownRare = this.transform.Find("DropdownRare").GetComponent<Dropdown>();
                }
                return this._DropdownRare;
            }
        }
        [SerializeField()]
        private Text _LabelTypeText;
        public Text LabelTypeText
        {
            get
            {
                if ((this._LabelTypeText == null))
                {
                    this._LabelTypeText = this.transform.Find("LabelType").GetComponent<Text>();
                }
                return this._LabelTypeText;
            }
        }
        [SerializeField()]
        private Dropdown _DropdownType;
        public Dropdown DropdownType
        {
            get
            {
                if ((this._DropdownType == null))
                {
                    this._DropdownType = this.transform.Find("DropdownType").GetComponent<Dropdown>();
                }
                return this._DropdownType;
            }
        }
        [SerializeField()]
        private Text _LabelSortText;
        public Text LabelSortText
        {
            get
            {
                if ((this._LabelSortText == null))
                {
                    this._LabelSortText = this.transform.Find("LabelSort").GetComponent<Text>();
                }
                return this._LabelSortText;
            }
        }
        [SerializeField()]
        private InputField _InputField;
        public InputField InputField
        {
            get
            {
                if ((this._InputField == null))
                {
                    this._InputField = this.transform.Find("InputField").GetComponent<InputField>();
                }
                return this._InputField;
            }
        }
        partial void onAwake();
    }
}
