//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class GameOptionItemText : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._TitleText = this.transform.Find("Title").GetComponent<Text>();
            this._InputField = this.transform.Find("InputField").GetComponent<InputField>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Text _TitleText;
        public Text TitleText
        {
            get
            {
                if ((this._TitleText == null))
                {
                    this._TitleText = this.transform.Find("Title").GetComponent<Text>();
                }
                return this._TitleText;
            }
        }
        [SerializeField()]
        private InputField _InputField;
        public InputField InputField
        {
            get
            {
                if ((this._InputField == null))
                {
                    this._InputField = this.transform.Find("InputField").GetComponent<InputField>();
                }
                return this._InputField;
            }
        }
        partial void onAwake();
    }
}
