//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Game : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._BackgroundImage = this.transform.Find("Background").GetComponent<Image>();
            this._Table = this.transform.Find("Table").GetComponent<Table>();
            this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
            this._GameResultDialog = this.transform.Find("GameResultDialog").GetComponent<GameResultDialog>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image _BackgroundImage;
        public Image BackgroundImage
        {
            get
            {
                if ((this._BackgroundImage == null))
                {
                    this._BackgroundImage = this.transform.Find("Background").GetComponent<Image>();
                }
                return this._BackgroundImage;
            }
        }
        [SerializeField()]
        private Table _Table;
        public Table Table
        {
            get
            {
                if ((this._Table == null))
                {
                    this._Table = this.transform.Find("Table").GetComponent<Table>();
                }
                return this._Table;
            }
        }
        [SerializeField()]
        private Button _QuitButton;
        public Button QuitButton
        {
            get
            {
                if ((this._QuitButton == null))
                {
                    this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
                }
                return this._QuitButton;
            }
        }
        [SerializeField()]
        private GameResultDialog _GameResultDialog;
        public GameResultDialog GameResultDialog
        {
            get
            {
                if ((this._GameResultDialog == null))
                {
                    this._GameResultDialog = this.transform.Find("GameResultDialog").GetComponent<GameResultDialog>();
                }
                return this._GameResultDialog;
            }
        }
        partial void onAwake();
    }
}
