//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Gem : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._Image = this.transform.Find("Image").GetComponent<Image>();
            this._Image_1 = this.transform.Find("Image (1)").GetComponent<Image>();
            this._Image_2 = this.transform.Find("Image (2)").GetComponent<Image>();
            this._Text = this.transform.Find("Text").GetComponent<Text>();
        }
        [SerializeField()]
        private Image _Image;
        public Image Image
        {
            get
            {
                if ((this._Image == null))
                {
                    this._Image = this.transform.Find("Image").GetComponent<Image>();
                }
                return this._Image;
            }
        }
        [SerializeField()]
        private Image _Image_1;
        public Image Image_1
        {
            get
            {
                if ((this._Image_1 == null))
                {
                    this._Image_1 = this.transform.Find("Image (1)").GetComponent<Image>();
                }
                return this._Image_1;
            }
        }
        [SerializeField()]
        private Image _Image_2;
        public Image Image_2
        {
            get
            {
                if ((this._Image_2 == null))
                {
                    this._Image_2 = this.transform.Find("Image (2)").GetComponent<Image>();
                }
                return this._Image_2;
            }
        }
        [SerializeField()]
        private Text _Text;
        public Text Text
        {
            get
            {
                if ((this._Text == null))
                {
                    this._Text = this.transform.Find("Text").GetComponent<Text>();
                }
                return this._Text;
            }
        }
        partial void onAwake();
    }
}
