//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class InitReplaceDialog : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._BlockerButton = this.transform.Find("Blocker").GetComponent<Button>();
            this._InitReplaceCardList = this.transform.Find("InitReplaceCardList").GetComponent<InitReplaceCardList>();
            this._ConfirmButton = this.transform.Find("Confirm").GetComponent<Button>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Button _BlockerButton;
        public Button BlockerButton
        {
            get
            {
                if ((this._BlockerButton == null))
                {
                    this._BlockerButton = this.transform.Find("Blocker").GetComponent<Button>();
                }
                return this._BlockerButton;
            }
        }
        [SerializeField()]
        private InitReplaceCardList _InitReplaceCardList;
        public InitReplaceCardList InitReplaceCardList
        {
            get
            {
                if ((this._InitReplaceCardList == null))
                {
                    this._InitReplaceCardList = this.transform.Find("InitReplaceCardList").GetComponent<InitReplaceCardList>();
                }
                return this._InitReplaceCardList;
            }
        }
        [SerializeField()]
        private Button _ConfirmButton;
        public Button ConfirmButton
        {
            get
            {
                if ((this._ConfirmButton == null))
                {
                    this._ConfirmButton = this.transform.Find("Confirm").GetComponent<Button>();
                }
                return this._ConfirmButton;
            }
        }
        partial void onAwake();
    }
}
