//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class LANPanel : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._CreateRoomButton = this.transform.Find("CreateRoomButton").GetComponent<Button>();
            this._FlushRoomButton = this.transform.Find("FlushRoomButton").GetComponent<Button>();
            this._RoomListPanelImage = this.transform.Find("RoomListPanel").GetComponent<Image>();
            this._RoomScrollView = this.transform.Find("RoomListPanel").Find("RoomScrollView").GetComponent<RoomScrollView>();
            this._LANGameText = this.transform.Find("RoomListPanel").Find("LANGameText").GetComponent<Text>();
            this._RoomInfoPanelImage = this.transform.Find("RoomInfoPanel").GetComponent<Image>();
            this._NameText = this.transform.Find("RoomInfoPanel").Find("NameText").GetComponent<Text>();
            this._IPText = this.transform.Find("RoomInfoPanel").Find("IPText").GetComponent<Text>();
            this._DescText = this.transform.Find("RoomInfoPanel").Find("DescText").GetComponent<Text>();
        }
        private NetworkingPageGroup _parent;
        public NetworkingPageGroup parent
        {
            get
            {
                return this.transform.parent.GetComponent<NetworkingPageGroup>();
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Button _CreateRoomButton;
        public Button CreateRoomButton
        {
            get
            {
                if ((this._CreateRoomButton == null))
                {
                    this._CreateRoomButton = this.transform.Find("CreateRoomButton").GetComponent<Button>();
                }
                return this._CreateRoomButton;
            }
        }
        [SerializeField()]
        private Button _FlushRoomButton;
        public Button FlushRoomButton
        {
            get
            {
                if ((this._FlushRoomButton == null))
                {
                    this._FlushRoomButton = this.transform.Find("FlushRoomButton").GetComponent<Button>();
                }
                return this._FlushRoomButton;
            }
        }
        [SerializeField()]
        private Image _RoomListPanelImage;
        public Image RoomListPanelImage
        {
            get
            {
                if ((this._RoomListPanelImage == null))
                {
                    this._RoomListPanelImage = this.transform.Find("RoomListPanel").GetComponent<Image>();
                }
                return this._RoomListPanelImage;
            }
        }
        [SerializeField()]
        private RoomScrollView _RoomScrollView;
        public RoomScrollView RoomScrollView
        {
            get
            {
                if ((this._RoomScrollView == null))
                {
                    this._RoomScrollView = this.transform.Find("RoomListPanel").Find("RoomScrollView").GetComponent<RoomScrollView>();
                }
                return this._RoomScrollView;
            }
        }
        [SerializeField()]
        private Text _LANGameText;
        public Text LANGameText
        {
            get
            {
                if ((this._LANGameText == null))
                {
                    this._LANGameText = this.transform.Find("RoomListPanel").Find("LANGameText").GetComponent<Text>();
                }
                return this._LANGameText;
            }
        }
        [SerializeField()]
        private Image _RoomInfoPanelImage;
        public Image RoomInfoPanelImage
        {
            get
            {
                if ((this._RoomInfoPanelImage == null))
                {
                    this._RoomInfoPanelImage = this.transform.Find("RoomInfoPanel").GetComponent<Image>();
                }
                return this._RoomInfoPanelImage;
            }
        }
        [SerializeField()]
        private Text _NameText;
        public Text NameText
        {
            get
            {
                if ((this._NameText == null))
                {
                    this._NameText = this.transform.Find("RoomInfoPanel").Find("NameText").GetComponent<Text>();
                }
                return this._NameText;
            }
        }
        [SerializeField()]
        private Text _IPText;
        public Text IPText
        {
            get
            {
                if ((this._IPText == null))
                {
                    this._IPText = this.transform.Find("RoomInfoPanel").Find("IPText").GetComponent<Text>();
                }
                return this._IPText;
            }
        }
        [SerializeField()]
        private Text _DescText;
        public Text DescText
        {
            get
            {
                if ((this._DescText == null))
                {
                    this._DescText = this.transform.Find("RoomInfoPanel").Find("DescText").GetComponent<Text>();
                }
                return this._DescText;
            }
        }
        partial void onAwake();
    }
}
