//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Loading : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._LoadingText = this.transform.Find("LoadingText").GetComponent<Text>();
            this._Text = this.transform.Find("Text").GetComponent<Text>();
            this._LoggerText = this.transform.Find("Logger").GetComponent<Text>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Text _LoadingText;
        public Text LoadingText
        {
            get
            {
                if ((this._LoadingText == null))
                {
                    this._LoadingText = this.transform.Find("LoadingText").GetComponent<Text>();
                }
                return this._LoadingText;
            }
        }
        [SerializeField()]
        private Text _Text;
        public Text Text
        {
            get
            {
                if ((this._Text == null))
                {
                    this._Text = this.transform.Find("Text").GetComponent<Text>();
                }
                return this._Text;
            }
        }
        [SerializeField()]
        private Text _LoggerText;
        public Text LoggerText
        {
            get
            {
                if ((this._LoggerText == null))
                {
                    this._LoggerText = this.transform.Find("Logger").GetComponent<Text>();
                }
                return this._LoggerText;
            }
        }
        partial void onAwake();
    }
}
