//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class MainMenu : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._BackgroundImage = this.transform.Find("BackgroundContainer").Find("Background").GetComponent<Image>();
            this._ButtonPanelImage = this.transform.Find("ButtonPanel").GetComponent<Image>();
            this._ButtonsVerticalLayoutGroup = this.transform.Find("ButtonPanel").Find("Buttons").GetComponent<VerticalLayoutGroup>();
            this._ManMachineButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("ManMachineButton").GetComponent<ButtonBlack>();
            this._NetworkButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("NetworkButton").GetComponent<ButtonBlack>();
            this._BuildButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("BuildButton").GetComponent<ButtonBlack>();
            this._AboutButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("AboutButton").GetComponent<ButtonBlack>();
            this._QuitButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("QuitButton").GetComponent<ButtonBlack>();
            this._LogoImage = this.transform.Find("Logo").GetComponent<Image>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image _BackgroundImage;
        public Image BackgroundImage
        {
            get
            {
                if ((this._BackgroundImage == null))
                {
                    this._BackgroundImage = this.transform.Find("BackgroundContainer").Find("Background").GetComponent<Image>();
                }
                return this._BackgroundImage;
            }
        }
        [SerializeField()]
        private Image _ButtonPanelImage;
        public Image ButtonPanelImage
        {
            get
            {
                if ((this._ButtonPanelImage == null))
                {
                    this._ButtonPanelImage = this.transform.Find("ButtonPanel").GetComponent<Image>();
                }
                return this._ButtonPanelImage;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _ButtonsVerticalLayoutGroup;
        public VerticalLayoutGroup ButtonsVerticalLayoutGroup
        {
            get
            {
                if ((this._ButtonsVerticalLayoutGroup == null))
                {
                    this._ButtonsVerticalLayoutGroup = this.transform.Find("ButtonPanel").Find("Buttons").GetComponent<VerticalLayoutGroup>();
                }
                return this._ButtonsVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private ButtonBlack _ManMachineButtonButtonBlack;
        public ButtonBlack ManMachineButtonButtonBlack
        {
            get
            {
                if ((this._ManMachineButtonButtonBlack == null))
                {
                    this._ManMachineButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("ManMachineButton").GetComponent<ButtonBlack>();
                }
                return this._ManMachineButtonButtonBlack;
            }
        }
        [SerializeField()]
        private ButtonBlack _NetworkButtonButtonBlack;
        public ButtonBlack NetworkButtonButtonBlack
        {
            get
            {
                if ((this._NetworkButtonButtonBlack == null))
                {
                    this._NetworkButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("NetworkButton").GetComponent<ButtonBlack>();
                }
                return this._NetworkButtonButtonBlack;
            }
        }
        [SerializeField()]
        private ButtonBlack _BuildButtonButtonBlack;
        public ButtonBlack BuildButtonButtonBlack
        {
            get
            {
                if ((this._BuildButtonButtonBlack == null))
                {
                    this._BuildButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("BuildButton").GetComponent<ButtonBlack>();
                }
                return this._BuildButtonButtonBlack;
            }
        }
        [SerializeField()]
        private ButtonBlack _AboutButtonButtonBlack;
        public ButtonBlack AboutButtonButtonBlack
        {
            get
            {
                if ((this._AboutButtonButtonBlack == null))
                {
                    this._AboutButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("AboutButton").GetComponent<ButtonBlack>();
                }
                return this._AboutButtonButtonBlack;
            }
        }
        [SerializeField()]
        private ButtonBlack _QuitButtonButtonBlack;
        public ButtonBlack QuitButtonButtonBlack
        {
            get
            {
                if ((this._QuitButtonButtonBlack == null))
                {
                    this._QuitButtonButtonBlack = this.transform.Find("ButtonPanel").Find("Buttons").Find("QuitButton").GetComponent<ButtonBlack>();
                }
                return this._QuitButtonButtonBlack;
            }
        }
        [SerializeField()]
        private Image _LogoImage;
        public Image LogoImage
        {
            get
            {
                if ((this._LogoImage == null))
                {
                    this._LogoImage = this.transform.Find("Logo").GetComponent<Image>();
                }
                return this._LogoImage;
            }
        }
        partial void onAwake();
    }
}
