//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class NetworkingPage : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._ReturnButton = this.transform.Find("ReturnButton").GetComponent<Button>();
            this._LinkButton = this.transform.Find("LinkButton").GetComponent<Button>();
            this._LANButton = this.transform.Find("LANButton").GetComponent<Button>();
            this._RoomButton = this.transform.Find("RoomButton").GetComponent<Button>();
            this._ControlPanelImage = this.transform.Find("ControlPanel").GetComponent<Image>();
            this._BtnGroupVerticalLayoutGroup = this.transform.Find("ControlPanel").Find("BtnGroup").GetComponent<VerticalLayoutGroup>();
            this._WANButton = this.transform.Find("ControlPanel").Find("BtnGroup").Find("WAN").GetComponent<Button>();
            this._NetworkDialogImage = this.transform.Find("NetworkDialog").GetComponent<Image>();
            this._DialogText = this.transform.Find("NetworkDialog").Find("DialogText").GetComponent<Text>();
            this._DialogButtonList = this.transform.Find("NetworkDialog").Find("DialogButtonList").GetComponent<DialogButtonList>();
            this._RemoteRoomScrollView = this.transform.Find("Remote").Find("RemoteRoomScrollView").GetComponent<RoomScrollView>();
            this._Text = this.transform.Find("Remote").Find("Text").GetComponent<Text>();
            this._NetworkingPageGroup = this.transform.Find("NetworkingPageGroup").GetComponent<NetworkingPageGroup>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Button _ReturnButton;
        public Button ReturnButton
        {
            get
            {
                if ((this._ReturnButton == null))
                {
                    this._ReturnButton = this.transform.Find("ReturnButton").GetComponent<Button>();
                }
                return this._ReturnButton;
            }
        }
        [SerializeField()]
        private Button _LinkButton;
        public Button LinkButton
        {
            get
            {
                if ((this._LinkButton == null))
                {
                    this._LinkButton = this.transform.Find("LinkButton").GetComponent<Button>();
                }
                return this._LinkButton;
            }
        }
        [SerializeField()]
        private Button _LANButton;
        public Button LANButton
        {
            get
            {
                if ((this._LANButton == null))
                {
                    this._LANButton = this.transform.Find("LANButton").GetComponent<Button>();
                }
                return this._LANButton;
            }
        }
        [SerializeField()]
        private Button _RoomButton;
        public Button RoomButton
        {
            get
            {
                if ((this._RoomButton == null))
                {
                    this._RoomButton = this.transform.Find("RoomButton").GetComponent<Button>();
                }
                return this._RoomButton;
            }
        }
        [SerializeField()]
        private Image _ControlPanelImage;
        public Image ControlPanelImage
        {
            get
            {
                if ((this._ControlPanelImage == null))
                {
                    this._ControlPanelImage = this.transform.Find("ControlPanel").GetComponent<Image>();
                }
                return this._ControlPanelImage;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _BtnGroupVerticalLayoutGroup;
        public VerticalLayoutGroup BtnGroupVerticalLayoutGroup
        {
            get
            {
                if ((this._BtnGroupVerticalLayoutGroup == null))
                {
                    this._BtnGroupVerticalLayoutGroup = this.transform.Find("ControlPanel").Find("BtnGroup").GetComponent<VerticalLayoutGroup>();
                }
                return this._BtnGroupVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private Button _WANButton;
        public Button WANButton
        {
            get
            {
                if ((this._WANButton == null))
                {
                    this._WANButton = this.transform.Find("ControlPanel").Find("BtnGroup").Find("WAN").GetComponent<Button>();
                }
                return this._WANButton;
            }
        }
        [SerializeField()]
        private Image _NetworkDialogImage;
        public Image NetworkDialogImage
        {
            get
            {
                if ((this._NetworkDialogImage == null))
                {
                    this._NetworkDialogImage = this.transform.Find("NetworkDialog").GetComponent<Image>();
                }
                return this._NetworkDialogImage;
            }
        }
        [SerializeField()]
        private Text _DialogText;
        public Text DialogText
        {
            get
            {
                if ((this._DialogText == null))
                {
                    this._DialogText = this.transform.Find("NetworkDialog").Find("DialogText").GetComponent<Text>();
                }
                return this._DialogText;
            }
        }
        [SerializeField()]
        private DialogButtonList _DialogButtonList;
        public DialogButtonList DialogButtonList
        {
            get
            {
                if ((this._DialogButtonList == null))
                {
                    this._DialogButtonList = this.transform.Find("NetworkDialog").Find("DialogButtonList").GetComponent<DialogButtonList>();
                }
                return this._DialogButtonList;
            }
        }
        [SerializeField()]
        private RoomScrollView _RemoteRoomScrollView;
        public RoomScrollView RemoteRoomScrollView
        {
            get
            {
                if ((this._RemoteRoomScrollView == null))
                {
                    this._RemoteRoomScrollView = this.transform.Find("Remote").Find("RemoteRoomScrollView").GetComponent<RoomScrollView>();
                }
                return this._RemoteRoomScrollView;
            }
        }
        [SerializeField()]
        private Text _Text;
        public Text Text
        {
            get
            {
                if ((this._Text == null))
                {
                    this._Text = this.transform.Find("Remote").Find("Text").GetComponent<Text>();
                }
                return this._Text;
            }
        }
        [SerializeField()]
        private NetworkingPageGroup _NetworkingPageGroup;
        public NetworkingPageGroup NetworkingPageGroup
        {
            get
            {
                if ((this._NetworkingPageGroup == null))
                {
                    this._NetworkingPageGroup = this.transform.Find("NetworkingPageGroup").GetComponent<NetworkingPageGroup>();
                }
                return this._NetworkingPageGroup;
            }
        }
        partial void onAwake();
    }
}
