//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class NewUI : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Canvas = this.GetComponent<Canvas>();
            this._Main = this.transform.Find("Main").GetComponent<Main>();
        }
        [SerializeField()]
        private Canvas m_as_Canvas;
        public Canvas asCanvas
        {
            get
            {
                if ((this.m_as_Canvas == null))
                {
                    this.m_as_Canvas = this.GetComponent<Canvas>();
                }
                return this.m_as_Canvas;
            }
        }
        [SerializeField()]
        private Main _Main;
        public Main Main
        {
            get
            {
                if ((this._Main == null))
                {
                    this._Main = this.transform.Find("Main").GetComponent<Main>();
                }
                return this._Main;
            }
        }
        partial void onAwake();
    }
}
