//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class PropNumber : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Text = this.GetComponent<Text>();
        }
        [SerializeField()]
        private Text m_as_Text;
        public Text asText
        {
            get
            {
                if ((this.m_as_Text == null))
                {
                    this.m_as_Text = this.GetComponent<Text>();
                }
                return this.m_as_Text;
            }
        }
        partial void onAwake();
    }
}
