//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomPlayerListItem : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Button = this.GetComponent<Button>();
            this.m_as_Image = this.GetComponent<Image>();
            this._NameText = this.transform.Find("NameText").GetComponent<Text>();
            this._CharacterText = this.transform.Find("CharacterText").GetComponent<Text>();
            this._Button = this.transform.Find("Button").GetComponent<Button>();
        }
        private RoomPlayerList _parent;
        public RoomPlayerList parent
        {
            get
            {
                return this.transform.parent.GetComponent<RoomPlayerList>();
            }
        }
        [SerializeField()]
        private Button m_as_Button;
        public Button asButton
        {
            get
            {
                if ((this.m_as_Button == null))
                {
                    this.m_as_Button = this.GetComponent<Button>();
                }
                return this.m_as_Button;
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Text _NameText;
        public Text NameText
        {
            get
            {
                if ((this._NameText == null))
                {
                    this._NameText = this.transform.Find("NameText").GetComponent<Text>();
                }
                return this._NameText;
            }
        }
        [SerializeField()]
        private Text _CharacterText;
        public Text CharacterText
        {
            get
            {
                if ((this._CharacterText == null))
                {
                    this._CharacterText = this.transform.Find("CharacterText").GetComponent<Text>();
                }
                return this._CharacterText;
            }
        }
        [SerializeField()]
        private Button _Button;
        public Button Button
        {
            get
            {
                if ((this._Button == null))
                {
                    this._Button = this.transform.Find("Button").GetComponent<Button>();
                }
                return this._Button;
            }
        }
        partial void onAwake();
    }
}
