//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomPanel : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._TitleBarImage = this.transform.Find("TitleBar").GetComponent<Image>();
            this._TitleText = this.transform.Find("TitleBar").Find("Title").GetComponent<Text>();
            this._IPText = this.transform.Find("TitleBar").Find("IP").GetComponent<Text>();
            this._RoomPlayerListScrollRect = this.transform.Find("RoomPlayerListScrollRect").GetComponent<ScrollRect>();
            this._RoomPlayerList = this.transform.Find("RoomPlayerListScrollRect").Find("Viewport").Find("RoomPlayerList").GetComponent<RoomPlayerList>();
            this._GameOptionPanelImage = this.transform.Find("GameOptionPanel").GetComponent<Image>();
            this._GameOptionPanelVerticalLayoutGroup = this.transform.Find("GameOptionPanel").GetComponent<VerticalLayoutGroup>();
            this._RandomSeedContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("RandomSeedContainer").GetComponent<GameOptionItemText>();
            this._ShuffleContainerGameOptionItemToggle = this.transform.Find("GameOptionPanel").Find("ShuffleContainer").GetComponent<GameOptionItemToggle>();
            this._InitReplacementContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("InitReplacementContainer").GetComponent<GameOptionItemText>();
            this._TurnTimeContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("TurnTimeContainer").GetComponent<GameOptionItemText>();
            this._IsSortedToggleGameOptionItemToggle = this.transform.Find("GameOptionPanel").Find("IsSortedToggle").GetComponent<GameOptionItemToggle>();
            this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
            this._StartButton = this.transform.Find("StartButton").GetComponent<Button>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.parent.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Image _TitleBarImage;
        public Image TitleBarImage
        {
            get
            {
                if ((this._TitleBarImage == null))
                {
                    this._TitleBarImage = this.transform.Find("TitleBar").GetComponent<Image>();
                }
                return this._TitleBarImage;
            }
        }
        [SerializeField()]
        private Text _TitleText;
        public Text TitleText
        {
            get
            {
                if ((this._TitleText == null))
                {
                    this._TitleText = this.transform.Find("TitleBar").Find("Title").GetComponent<Text>();
                }
                return this._TitleText;
            }
        }
        [SerializeField()]
        private Text _IPText;
        public Text IPText
        {
            get
            {
                if ((this._IPText == null))
                {
                    this._IPText = this.transform.Find("TitleBar").Find("IP").GetComponent<Text>();
                }
                return this._IPText;
            }
        }
        [SerializeField()]
        private ScrollRect _RoomPlayerListScrollRect;
        public ScrollRect RoomPlayerListScrollRect
        {
            get
            {
                if ((this._RoomPlayerListScrollRect == null))
                {
                    this._RoomPlayerListScrollRect = this.transform.Find("RoomPlayerListScrollRect").GetComponent<ScrollRect>();
                }
                return this._RoomPlayerListScrollRect;
            }
        }
        [SerializeField()]
        private RoomPlayerList _RoomPlayerList;
        public RoomPlayerList RoomPlayerList
        {
            get
            {
                if ((this._RoomPlayerList == null))
                {
                    this._RoomPlayerList = this.transform.Find("RoomPlayerListScrollRect").Find("Viewport").Find("RoomPlayerList").GetComponent<RoomPlayerList>();
                }
                return this._RoomPlayerList;
            }
        }
        [SerializeField()]
        private Image _GameOptionPanelImage;
        public Image GameOptionPanelImage
        {
            get
            {
                if ((this._GameOptionPanelImage == null))
                {
                    this._GameOptionPanelImage = this.transform.Find("GameOptionPanel").GetComponent<Image>();
                }
                return this._GameOptionPanelImage;
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup _GameOptionPanelVerticalLayoutGroup;
        public VerticalLayoutGroup GameOptionPanelVerticalLayoutGroup
        {
            get
            {
                if ((this._GameOptionPanelVerticalLayoutGroup == null))
                {
                    this._GameOptionPanelVerticalLayoutGroup = this.transform.Find("GameOptionPanel").GetComponent<VerticalLayoutGroup>();
                }
                return this._GameOptionPanelVerticalLayoutGroup;
            }
        }
        [SerializeField()]
        private GameOptionItemText _RandomSeedContainerGameOptionItemText;
        public GameOptionItemText RandomSeedContainerGameOptionItemText
        {
            get
            {
                if ((this._RandomSeedContainerGameOptionItemText == null))
                {
                    this._RandomSeedContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("RandomSeedContainer").GetComponent<GameOptionItemText>();
                }
                return this._RandomSeedContainerGameOptionItemText;
            }
        }
        [SerializeField()]
        private GameOptionItemToggle _ShuffleContainerGameOptionItemToggle;
        public GameOptionItemToggle ShuffleContainerGameOptionItemToggle
        {
            get
            {
                if ((this._ShuffleContainerGameOptionItemToggle == null))
                {
                    this._ShuffleContainerGameOptionItemToggle = this.transform.Find("GameOptionPanel").Find("ShuffleContainer").GetComponent<GameOptionItemToggle>();
                }
                return this._ShuffleContainerGameOptionItemToggle;
            }
        }
        [SerializeField()]
        private GameOptionItemText _InitReplacementContainerGameOptionItemText;
        public GameOptionItemText InitReplacementContainerGameOptionItemText
        {
            get
            {
                if ((this._InitReplacementContainerGameOptionItemText == null))
                {
                    this._InitReplacementContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("InitReplacementContainer").GetComponent<GameOptionItemText>();
                }
                return this._InitReplacementContainerGameOptionItemText;
            }
        }
        [SerializeField()]
        private GameOptionItemText _TurnTimeContainerGameOptionItemText;
        public GameOptionItemText TurnTimeContainerGameOptionItemText
        {
            get
            {
                if ((this._TurnTimeContainerGameOptionItemText == null))
                {
                    this._TurnTimeContainerGameOptionItemText = this.transform.Find("GameOptionPanel").Find("TurnTimeContainer").GetComponent<GameOptionItemText>();
                }
                return this._TurnTimeContainerGameOptionItemText;
            }
        }
        [SerializeField()]
        private GameOptionItemToggle _IsSortedToggleGameOptionItemToggle;
        public GameOptionItemToggle IsSortedToggleGameOptionItemToggle
        {
            get
            {
                if ((this._IsSortedToggleGameOptionItemToggle == null))
                {
                    this._IsSortedToggleGameOptionItemToggle = this.transform.Find("GameOptionPanel").Find("IsSortedToggle").GetComponent<GameOptionItemToggle>();
                }
                return this._IsSortedToggleGameOptionItemToggle;
            }
        }
        [SerializeField()]
        private Button _QuitButton;
        public Button QuitButton
        {
            get
            {
                if ((this._QuitButton == null))
                {
                    this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
                }
                return this._QuitButton;
            }
        }
        [SerializeField()]
        private Button _StartButton;
        public Button StartButton
        {
            get
            {
                if ((this._StartButton == null))
                {
                    this._StartButton = this.transform.Find("StartButton").GetComponent<Button>();
                }
                return this._StartButton;
            }
        }
        partial void onAwake();
    }
}
