//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomPlayerList : UIList<RoomPlayerListItem>
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.defaultItem.gameObject.SetActive(false);
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_VerticalLayoutGroup = this.GetComponent<VerticalLayoutGroup>();
            this.defaultItem = this.transform.Find("RoomPlayerListItem").GetComponent<RoomPlayerListItem>();
        }
        private Main _parent;
        public Main parent
        {
            get
            {
                return this.transform.parent.parent.parent.parent.parent.GetComponent<Main>();
            }
        }
        [SerializeField()]
        private VerticalLayoutGroup m_as_VerticalLayoutGroup;
        public VerticalLayoutGroup asVerticalLayoutGroup
        {
            get
            {
                if ((this.m_as_VerticalLayoutGroup == null))
                {
                    this.m_as_VerticalLayoutGroup = this.GetComponent<VerticalLayoutGroup>();
                }
                return this.m_as_VerticalLayoutGroup;
            }
        }
        protected override RoomPlayerListItem getDefaultItem()
        {
            return this.transform.Find("RoomPlayerListItem").GetComponent<RoomPlayerListItem>();
        }
        partial void onAwake();
    }
}
