//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomScrollView : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this.m_as_ScrollRect = this.GetComponent<ScrollRect>();
            this._ViewportMask = this.transform.Find("Viewport").GetComponent<Mask>();
            this._RoomList = this.transform.Find("Viewport").Find("RoomList").GetComponent<RoomList>();
            this._Scrollbar_VerticalImage = this.transform.Find("Scrollbar Vertical").GetComponent<Image>();
            this._Scrollbar_Vertical = this.transform.Find("Scrollbar Vertical").GetComponent<Scrollbar>();
            this._HandleImage = this.transform.Find("Scrollbar Vertical").Find("Sliding Area").Find("Handle").GetComponent<Image>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private ScrollRect m_as_ScrollRect;
        public ScrollRect asScrollRect
        {
            get
            {
                if ((this.m_as_ScrollRect == null))
                {
                    this.m_as_ScrollRect = this.GetComponent<ScrollRect>();
                }
                return this.m_as_ScrollRect;
            }
        }
        [SerializeField()]
        private Mask _ViewportMask;
        public Mask ViewportMask
        {
            get
            {
                if ((this._ViewportMask == null))
                {
                    this._ViewportMask = this.transform.Find("Viewport").GetComponent<Mask>();
                }
                return this._ViewportMask;
            }
        }
        [SerializeField()]
        private RoomList _RoomList;
        public RoomList RoomList
        {
            get
            {
                if ((this._RoomList == null))
                {
                    this._RoomList = this.transform.Find("Viewport").Find("RoomList").GetComponent<RoomList>();
                }
                return this._RoomList;
            }
        }
        [SerializeField()]
        private Image _Scrollbar_VerticalImage;
        public Image Scrollbar_VerticalImage
        {
            get
            {
                if ((this._Scrollbar_VerticalImage == null))
                {
                    this._Scrollbar_VerticalImage = this.transform.Find("Scrollbar Vertical").GetComponent<Image>();
                }
                return this._Scrollbar_VerticalImage;
            }
        }
        [SerializeField()]
        private Scrollbar _Scrollbar_Vertical;
        public Scrollbar Scrollbar_Vertical
        {
            get
            {
                if ((this._Scrollbar_Vertical == null))
                {
                    this._Scrollbar_Vertical = this.transform.Find("Scrollbar Vertical").GetComponent<Scrollbar>();
                }
                return this._Scrollbar_Vertical;
            }
        }
        [SerializeField()]
        private Image _HandleImage;
        public Image HandleImage
        {
            get
            {
                if ((this._HandleImage == null))
                {
                    this._HandleImage = this.transform.Find("Scrollbar Vertical").Find("Sliding Area").Find("Handle").GetComponent<Image>();
                }
                return this._HandleImage;
            }
        }
        partial void onAwake();
    }
}
