//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomScrollView : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this.m_as_ScrollRect = this.GetComponent<ScrollRect>();
            this._ViewportMask = this.transform.Find("Viewport").GetComponent<Mask>();
            this._RoomList = this.transform.Find("Viewport").Find("RoomList").GetComponent<RoomList>();
            this._Scrollbar_VerticalScrollbarVertical = this.transform.Find("Scrollbar Vertical").GetComponent<ScrollbarVertical>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private ScrollRect m_as_ScrollRect;
        public ScrollRect asScrollRect
        {
            get
            {
                if ((this.m_as_ScrollRect == null))
                {
                    this.m_as_ScrollRect = this.GetComponent<ScrollRect>();
                }
                return this.m_as_ScrollRect;
            }
        }
        [SerializeField()]
        private Mask _ViewportMask;
        public Mask ViewportMask
        {
            get
            {
                if ((this._ViewportMask == null))
                {
                    this._ViewportMask = this.transform.Find("Viewport").GetComponent<Mask>();
                }
                return this._ViewportMask;
            }
        }
        [SerializeField()]
        private RoomList _RoomList;
        public RoomList RoomList
        {
            get
            {
                if ((this._RoomList == null))
                {
                    this._RoomList = this.transform.Find("Viewport").Find("RoomList").GetComponent<RoomList>();
                }
                return this._RoomList;
            }
        }
        [SerializeField()]
        private ScrollbarVertical _Scrollbar_VerticalScrollbarVertical;
        public ScrollbarVertical Scrollbar_VerticalScrollbarVertical
        {
            get
            {
                if ((this._Scrollbar_VerticalScrollbarVertical == null))
                {
                    this._Scrollbar_VerticalScrollbarVertical = this.transform.Find("Scrollbar Vertical").GetComponent<ScrollbarVertical>();
                }
                return this._Scrollbar_VerticalScrollbarVertical;
            }
        }
        partial void onAwake();
    }
}
