//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class RoomPanel : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this._RoomPlayerListScrollRect = this.transform.Find("RoomPlayerListScrollRect").GetComponent<ScrollRect>();
            this._RoomPlayerList = this.transform.Find("RoomPlayerListScrollRect").Find("Viewport").Find("RoomPlayerList").GetComponent<RoomPlayerList>();
            this._GameOptionPanelImage = this.transform.Find("GameOptionPanel").GetComponent<Image>();
            this._RandomSeedText = this.transform.Find("GameOptionPanel").Find("RandomSeedText").GetComponent<Text>();
            this._RandomSeedInputField = this.transform.Find("GameOptionPanel").Find("RandomSeedInputField").GetComponent<InputField>();
            this._ShuffleToggle = this.transform.Find("GameOptionPanel").Find("ShuffleToggle").GetComponent<Toggle>();
            this._InitReplaceTimeText = this.transform.Find("GameOptionPanel").Find("InitReplaceTimeText").GetComponent<Text>();
            this._InitReplaceTimeInputField = this.transform.Find("GameOptionPanel").Find("InitReplaceTimeInputField").GetComponent<InputField>();
            this._TurnTimeText = this.transform.Find("GameOptionPanel").Find("TurnTimeText").GetComponent<Text>();
            this._TurnTimeInputField = this.transform.Find("GameOptionPanel").Find("TurnTimeInputField").GetComponent<InputField>();
            this._IsSortedToggle = this.transform.Find("GameOptionPanel").Find("IsSortedToggle").GetComponent<Toggle>();
            this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
            this._StartButton = this.transform.Find("StartButton").GetComponent<Button>();
        }
        private NetworkingPageGroup _parent;
        public NetworkingPageGroup parent
        {
            get
            {
                return this.transform.parent.GetComponent<NetworkingPageGroup>();
            }
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private ScrollRect _RoomPlayerListScrollRect;
        public ScrollRect RoomPlayerListScrollRect
        {
            get
            {
                if ((this._RoomPlayerListScrollRect == null))
                {
                    this._RoomPlayerListScrollRect = this.transform.Find("RoomPlayerListScrollRect").GetComponent<ScrollRect>();
                }
                return this._RoomPlayerListScrollRect;
            }
        }
        [SerializeField()]
        private RoomPlayerList _RoomPlayerList;
        public RoomPlayerList RoomPlayerList
        {
            get
            {
                if ((this._RoomPlayerList == null))
                {
                    this._RoomPlayerList = this.transform.Find("RoomPlayerListScrollRect").Find("Viewport").Find("RoomPlayerList").GetComponent<RoomPlayerList>();
                }
                return this._RoomPlayerList;
            }
        }
        [SerializeField()]
        private Image _GameOptionPanelImage;
        public Image GameOptionPanelImage
        {
            get
            {
                if ((this._GameOptionPanelImage == null))
                {
                    this._GameOptionPanelImage = this.transform.Find("GameOptionPanel").GetComponent<Image>();
                }
                return this._GameOptionPanelImage;
            }
        }
        [SerializeField()]
        private Text _RandomSeedText;
        public Text RandomSeedText
        {
            get
            {
                if ((this._RandomSeedText == null))
                {
                    this._RandomSeedText = this.transform.Find("GameOptionPanel").Find("RandomSeedText").GetComponent<Text>();
                }
                return this._RandomSeedText;
            }
        }
        [SerializeField()]
        private InputField _RandomSeedInputField;
        public InputField RandomSeedInputField
        {
            get
            {
                if ((this._RandomSeedInputField == null))
                {
                    this._RandomSeedInputField = this.transform.Find("GameOptionPanel").Find("RandomSeedInputField").GetComponent<InputField>();
                }
                return this._RandomSeedInputField;
            }
        }
        [SerializeField()]
        private Toggle _ShuffleToggle;
        public Toggle ShuffleToggle
        {
            get
            {
                if ((this._ShuffleToggle == null))
                {
                    this._ShuffleToggle = this.transform.Find("GameOptionPanel").Find("ShuffleToggle").GetComponent<Toggle>();
                }
                return this._ShuffleToggle;
            }
        }
        [SerializeField()]
        private Text _InitReplaceTimeText;
        public Text InitReplaceTimeText
        {
            get
            {
                if ((this._InitReplaceTimeText == null))
                {
                    this._InitReplaceTimeText = this.transform.Find("GameOptionPanel").Find("InitReplaceTimeText").GetComponent<Text>();
                }
                return this._InitReplaceTimeText;
            }
        }
        [SerializeField()]
        private InputField _InitReplaceTimeInputField;
        public InputField InitReplaceTimeInputField
        {
            get
            {
                if ((this._InitReplaceTimeInputField == null))
                {
                    this._InitReplaceTimeInputField = this.transform.Find("GameOptionPanel").Find("InitReplaceTimeInputField").GetComponent<InputField>();
                }
                return this._InitReplaceTimeInputField;
            }
        }
        [SerializeField()]
        private Text _TurnTimeText;
        public Text TurnTimeText
        {
            get
            {
                if ((this._TurnTimeText == null))
                {
                    this._TurnTimeText = this.transform.Find("GameOptionPanel").Find("TurnTimeText").GetComponent<Text>();
                }
                return this._TurnTimeText;
            }
        }
        [SerializeField()]
        private InputField _TurnTimeInputField;
        public InputField TurnTimeInputField
        {
            get
            {
                if ((this._TurnTimeInputField == null))
                {
                    this._TurnTimeInputField = this.transform.Find("GameOptionPanel").Find("TurnTimeInputField").GetComponent<InputField>();
                }
                return this._TurnTimeInputField;
            }
        }
        [SerializeField()]
        private Toggle _IsSortedToggle;
        public Toggle IsSortedToggle
        {
            get
            {
                if ((this._IsSortedToggle == null))
                {
                    this._IsSortedToggle = this.transform.Find("GameOptionPanel").Find("IsSortedToggle").GetComponent<Toggle>();
                }
                return this._IsSortedToggle;
            }
        }
        [SerializeField()]
        private Button _QuitButton;
        public Button QuitButton
        {
            get
            {
                if ((this._QuitButton == null))
                {
                    this._QuitButton = this.transform.Find("QuitButton").GetComponent<Button>();
                }
                return this._QuitButton;
            }
        }
        [SerializeField()]
        private Button _StartButton;
        public Button StartButton
        {
            get
            {
                if ((this._StartButton == null))
                {
                    this._StartButton = this.transform.Find("StartButton").GetComponent<Button>();
                }
                return this._StartButton;
            }
        }
        partial void onAwake();
    }
}
