//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class ScrollbarVertical : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this.m_as_Image = this.GetComponent<Image>();
            this.m_as_Scrollbar = this.GetComponent<Scrollbar>();
            this._HandleImage = this.transform.Find("Sliding Area").Find("Handle").GetComponent<Image>();
        }
        [SerializeField()]
        private Image m_as_Image;
        public Image asImage
        {
            get
            {
                if ((this.m_as_Image == null))
                {
                    this.m_as_Image = this.GetComponent<Image>();
                }
                return this.m_as_Image;
            }
        }
        [SerializeField()]
        private Scrollbar m_as_Scrollbar;
        public Scrollbar asScrollbar
        {
            get
            {
                if ((this.m_as_Scrollbar == null))
                {
                    this.m_as_Scrollbar = this.GetComponent<Scrollbar>();
                }
                return this.m_as_Scrollbar;
            }
        }
        [SerializeField()]
        private Image _HandleImage;
        public Image HandleImage
        {
            get
            {
                if ((this._HandleImage == null))
                {
                    this._HandleImage = this.transform.Find("Sliding Area").Find("Handle").GetComponent<Image>();
                }
                return this._HandleImage;
            }
        }
        partial void onAwake();
    }
}
