//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.UI;
    
    public partial class Weather : UIObject
    {
        protected override void Awake()
        {
            base.Awake();
            this.autoBind();
            this.onAwake();
        }
        public void autoBind()
        {
            this._Mask = this.transform.Find("Mask").GetComponent<Mask>();
            this._IconImage = this.transform.Find("Mask").Find("Icon").GetComponent<Image>();
            this._FrameImage = this.transform.Find("Frame").GetComponent<Image>();
        }
        [SerializeField()]
        private Mask _Mask;
        public Mask Mask
        {
            get
            {
                if ((this._Mask == null))
                {
                    this._Mask = this.transform.Find("Mask").GetComponent<Mask>();
                }
                return this._Mask;
            }
        }
        [SerializeField()]
        private Image _IconImage;
        public Image IconImage
        {
            get
            {
                if ((this._IconImage == null))
                {
                    this._IconImage = this.transform.Find("Mask").Find("Icon").GetComponent<Image>();
                }
                return this._IconImage;
            }
        }
        [SerializeField()]
        private Image _FrameImage;
        public Image FrameImage
        {
            get
            {
                if ((this._FrameImage == null))
                {
                    this._FrameImage = this.transform.Find("Frame").GetComponent<Image>();
                }
                return this._FrameImage;
            }
        }
        partial void onAwake();
    }
}
